In [41]:
import pandas as pd
import numpy as np
import requests
import glob
import os
import datetime
print('Completed import lib')

Completed import lib

In [42]:
data = pd.read_excel(r"C:\Users\hieudd\Downloads\2011\Thang 12-2011\06-12-2011\06122011 - NDTNN (Foreign Trading).xls", skiprows=0)
data.head(20)

,KẾT QUẢ GIAO DỊCH CỔ PHIẾU VÀ CHỨNG CHỈ QUỸ CỦA NHÀ ĐẦU TƯ NƯỚC NGOÀI TRONG NGÀY,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mã CK\n(Securities),KL được phép sở hữu (Total Room),KL còn được phép mua đầu ngày (Current Room),% SH nước ngoài (Foreign Owned Ratio),% SH Nhà nước (State Owned Ratio),Khớp lệnh (Order Maching),NaN,NaN,NaN,NaN,NaN,Thỏa thuận (Putthrough),NaN,Tổng cộng (Total),NaN
2,NaN,NaN,NaN,NaN,NaN,KL mua (Buying Vol.),NaN,NaN,KL bán (Selling Vol.),NaN,NaN,KL mua (Buying Vol.),KL bán (Selling Vol.),KL mua (Buying Vol.),KL bán (Selling Vol.)
3,NaN,NaN,NaN,NaN,NaN,Đợt mở cửa (Pre-Open),Đợt GDLT (Cont),Đợt đóng cửa (Pre-Close),Đợt mở cửa (Pre-Open),Đợt GDLT (Cont),Đợt đóng cửa (Pre-Close),NaN,NaN,NaN,NaN
4,Sum -->,8584611610,5239681374,NaN,NaN,295430,2018830,213030,402220,1644610,191980,856470,816470,3383760,3055280
5,AAM,5556533,5386953,1.495432,0,0,0,0,0,0,0,0,0,0,0
6,ABT,6667531,5216212,10.665811,0,0,0,0,0,8650,1530,0,0,0,10180
7,ACC,4900000,4874800,0.252,73.36704,0,0,0,0,0,0,0,0,0,0
8,ACL,5390000,4926081,4.217445,0,0,0,0,0,0,0,0,0,0,0
9,AGD,5879966,5804495,0.628929,0,0,0,0,0,0,0,0,0,0,0
10,AGF,6301051,5773610,4.101635,8.24,0,0,0,0,0,0,0,0,0,0
11,AGR,103880000,103142391,0.347929,74.62,0,0,0,0,0,0,0,0,0,0
12,ALP,31646362,28602771,4.712578,0,1000,0,0,0,0,0,0,0,1000,0
13,ANV,32340000,31061003,1.937874,0,0,0,0,0,0,0,0,0,0,0
14,APC,5609520,4370665,10.821585,0,0,0,0,0,0,0,0,0,0,0
15,ASM,19470739,17618646,4.660971,0,0,0,0,0,0,0,0,0,0,0
16,ASP,11186698,8130757,13.38564,0,0,0,0,0,0,0,0,0,0,0
17,ATA,4900000,4702090,1.9791,0,0,0,0,0,0,0,0,0,0,0
18,AVF,11025000,8552607,10.988413,0,0,0,0,0,0,0,0,0,0,0
19,BAS,4704000,4700570,0.035729,0,0,0,0,0,0,0,0,0,0,0

In [43]:
data.columns

Index(['KẾT QUẢ GIAO DỊCH CỔ PHIẾU VÀ CHỨNG CHỈ QUỸ CỦA NHÀ ĐẦU TƯ NƯỚC NGOÀI TRONG NGÀY',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [44]:
data.columns.tolist()[0]

'KẾT QUẢ GIAO DỊCH CỔ PHIẾU VÀ CHỨNG CHỈ QUỸ CỦA NHÀ ĐẦU TƯ NƯỚC NGOÀI TRONG NGÀY'

In [45]:
len(data.columns) - 2

13

In [46]:
data.shape[1]-2

13

In [47]:
data[data[data.columns.tolist()[0]].str.len() == 3]

,KẾT QUẢ GIAO DỊCH CỔ PHIẾU VÀ CHỨNG CHỈ QUỸ CỦA NHÀ ĐẦU TƯ NƯỚC NGOÀI TRONG NGÀY,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
5,AAM,5556533,5386953,1.495432,0,0,0,0,0,0,0,0,0,0,0
6,ABT,6667531,5216212,10.665811,0,0,0,0,0,8650,1530,0,0,0,10180
7,ACC,4900000,4874800,0.252,73.36704,0,0,0,0,0,0,0,0,0,0
8,ACL,5390000,4926081,4.217445,0,0,0,0,0,0,0,0,0,0,0
9,AGD,5879966,5804495,0.628929,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,VSI,6468000,6442210,0.195379,60,0,0,0,0,0,0,0,0,0,0
307,VST,28909675,28685292,0.380314,60,0,0,0,0,0,0,0,0,0,0
308,VTB,5871205,5805639,0.547202,55.457196,0,0,0,0,0,0,0,0,0,0
309,VTF,8832499,8809399,0.128152,0,0,0,0,0,0,0,0,0,0,0
310,VTO,39134666,38270820,1.08161,51.918052,0,0,0,0,0,0,0,0,0,0

In [48]:
root.split("\\")[-1]

'29-03-2013'

In [49]:
DTNN_2011_2012 = pd.DataFrame()

for a in (2011,2012):
    path = 'C:/Users/hieudd/Downloads/%s' %a
    extension = 'xls'
    for root, dirs, files in os.walk(path):
        for i in files:
            for j in files:
                if((i.endswith('(Foreign Trading).xls'))&(j.startswith('NN'))):
                    FT = os.path.join(root,i)
                    NN = os.path.join(root,j)
                    data = pd.read_excel(r'%s' %FT, skiprows=4)
                    data = data.iloc[:,0:13]
                    data.drop(data.head(1).index,inplace=True)
                    data.drop(data.tail(2).index,inplace=True)
                    data.reset_index(inplace=True)
                    data['Date'] = root.split("\\")[-1]
                    data.set_axis(['STT','Ticker','Total Room','Current Room','Foreign Owned Ratio',' State Owned Ratio',
                                        'OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close',
                                        'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close',
                                        'Putthrough_Buying_Vol','Putthrough_Selling_Vol.','Date'], axis=1, inplace=True)
                    df = pd.read_excel(r'%s' %NN, sheet_name='Chi tiet (Details)', skiprows=10)
                    df.drop(df.tail(2).index,inplace=True)
                    df.set_axis(['stt',	'Ticker','KL GD mua thị trường','KL GD mua thị trường %','KL GD bán thị trường',
                                'KL GD bán thị trường %','OrderM_Buy_vol.Buying value',
                                'GT giao dịch mua toàn thị trường %','OrderM_Sell_vol.Selling-value',
                                'GT giao dịch bán toàn thị trường %','KL GD Mua thoa thuan','KL GD Mua thoa thuan %',
                                'KL GD Ban thoa thuan','KL GD Ban thoa thuan %','Putthrough_Buying Val',
                                'GTr GD mua thoa thuan %','Putthrough_Selling Va','GTr GD bán thoa thuan %'],axis=1, inplace=True)
                    cd = pd.merge(data, df ,how='left', on='Ticker')
                    cd = cd[['STT','Ticker','Total Room','Current Room','Foreign Owned Ratio',' State Owned Ratio',
                            'OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close','OrderM_Buy_vol.Buying value',
                            'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close','OrderM_Sell_vol.Selling-value',
                            'Putthrough_Buying_Vol','Putthrough_Buying Val','Putthrough_Selling_Vol.','Putthrough_Selling Va','Date']]
                    DTNN_2011_2012 = pd.concat([DTNN_2011_2012,cd])

In [60]:
DTNN_2011_2012.shape

tuple

In [51]:
DTNN_2011_2012

,STT,Ticker,Total Room,Current Room,Foreign Owned Ratio,State Owned Ratio,OrderM_Buy_vol.Pre-Open,OrderM_Buy_vol.Cont,OrderM_Buy_vol.Pre-Close,OrderM_Buy_vol.Buying value,OrderM_Sell_vol.Pre-Open,OrderM_Sell_vol.Cont,OrderM_Sell_vol.Pre-Close,OrderM_Sell_vol.Selling-value,Putthrough_Buying_Vol,Putthrough_Buying Val,Putthrough_Selling_Vol.,Putthrough_Selling Va,Date
0,1,AAM,5556533.36,5393393.0,1.438645,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
1,2,ABT,6667531.43,4544944.0,15.598994,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
2,3,ACL,5390000.00,4901958.0,4.436745,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
3,4,AGD,3920000.00,3828660.0,1.14175,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
4,5,AGF,6301051.12,5627483.0,5.237989,8.189668,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,311,VST,28909675.00,28641763.0,0.454093,60.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,28-12-2012
311,312,VTB,5871205.00,5718749.0,1.27237,55.540000,0.0,2000.0,1600.0,26200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28-12-2012
312,313,VTF,10302499.00,9972589.0,1.569094,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,28-12-2012
313,314,VTO,39134666.00,37476616.0,2.076023,51.918052,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,28-12-2012
314,315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28-12-2012

In [52]:
DTNN_2013 = pd.DataFrame()

path = 'C:/Users/hieudd/Downloads/2013'
extension = 'xls'
for root, dirs, files in os.walk(path):
    for i in files:
        for j in files:
            if((i.endswith('(Foreign Trading).xls'))&(j.startswith('NN'))):
                FT = os.path.join(root,i)
                NN = os.path.join(root,j)
                data = pd.read_excel(r'%s' %FT, skiprows=4)
                data = data.iloc[:,0:13]
                data.drop(data.head(1).index,inplace=True)
                data.drop(data.tail(2).index,inplace=True)
                data.reset_index(inplace=True)
                data['Date'] = root[39:]
                data.set_axis(['STT','Ticker','Total Room','Current Room','Foreign Owned Ratio',' State Owned Ratio',
                                    'OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close',
                                    'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close',
                                    'Putthrough_Buying_Vol','Putthrough_Selling_Vol.','Date'], axis=1, inplace=True)
                df = pd.read_excel(r'%s' %NN, sheet_name='Chi tiet (Details)', skiprows=10)
                df.drop(df.tail(2).index,inplace=True)
                df.set_axis(['stt',	'Ticker','KL GD mua thị trường','KL GD mua thị trường %','KL GD bán thị trường',
                            'KL GD bán thị trường %','OrderM_Buy_vol.Buying value',
                            'GT giao dịch mua toàn thị trường %','OrderM_Sell_vol.Selling-value',
                            'GT giao dịch bán toàn thị trường %','KL GD Mua thoa thuan','KL GD Mua thoa thuan %',
                            'KL GD Ban thoa thuan','KL GD Ban thoa thuan %','Putthrough_Buying Val',
                            'GTr GD mua thoa thuan %','Putthrough_Selling Va','GTr GD bán thoa thuan %'],axis=1, inplace=True)
                cd = pd.merge(data, df ,how='left', on='Ticker')
                cd = cd[['STT','Ticker','Total Room','Current Room','Foreign Owned Ratio',' State Owned Ratio',
                        'OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close','OrderM_Buy_vol.Buying value',
                        'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close','OrderM_Sell_vol.Selling-value',
                        'Putthrough_Buying_Vol','Putthrough_Buying Val','Putthrough_Selling_Vol.','Putthrough_Selling Va','Date']]
                DTNN_2013 = pd.concat([DTNN_2013,cd])
DTNN_2013.dropna(axis=0, how='all', inplace=True)

In [53]:
DTNN_2013.shape

(1260, 19)

In [54]:
DTNN_2013_2 = pd.DataFrame()

path = 'C:/Users/hieudd/Downloads/2013q1'
extension = 'xls'
for root, dirs, files in os.walk(path):
    for i in files:
        if((i.endswith('Foreign trade).xls'))):
            FT = os.path.join(root,i)
            data = pd.read_excel(r'%s' %FT, sheet_name=1)
            data.drop(data.head(9).index,inplace=True)
            # data.drop(data.tail(4).index,inplace=True)
            data['Date'] = root[47:]
            data.reset_index(inplace=True)
            data.set_axis(['STT','Ticker','Total Room','Current Room','Foreign Owned Ratio',' State Owned Ratio',
                    'OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close','OrderM_Buy_vol.Buying value',
                    'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close','OrderM_Sell_vol.Selling-value',
                    'Putthrough_Buying_Vol','Putthrough_Buying Val','Putthrough_Selling_Vol.','Putthrough_Selling Va','Date'], axis=1, inplace=True) 
            data = data[[
                        'Ticker','OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close','OrderM_Buy_vol.Buying value',
                        'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close','OrderM_Sell_vol.Selling-value',
                        'Putthrough_Buying_Vol','Putthrough_Buying Val','Putthrough_Selling_Vol.','Putthrough_Selling Va','Date']]
            DTNN_2013_2 = pd.concat([DTNN_2013_2,data])

In [55]:
DTNN_2013_2.shape

(17121, 14)

In [56]:
DTNN = pd.concat([DTNN_2011_2012,DTNN_2013,DTNN_2013_2])
print(DTNN.shape)
DTNN

(168644, 19)

,STT,Ticker,Total Room,Current Room,Foreign Owned Ratio,State Owned Ratio,OrderM_Buy_vol.Pre-Open,OrderM_Buy_vol.Cont,OrderM_Buy_vol.Pre-Close,OrderM_Buy_vol.Buying value,OrderM_Sell_vol.Pre-Open,OrderM_Sell_vol.Cont,OrderM_Sell_vol.Pre-Close,OrderM_Sell_vol.Selling-value,Putthrough_Buying_Vol,Putthrough_Buying Val,Putthrough_Selling_Vol.,Putthrough_Selling Va,Date
0,1.0,AAM,5556533.36,5393393.0,1.438645,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
1,2.0,ABT,6667531.43,4544944.0,15.598994,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
2,3.0,ACL,5390000.00,4901958.0,4.436745,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
3,4.0,AGD,3920000.00,3828660.0,1.14175,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
4,5.0,AGF,6301051.12,5627483.0,5.237989,8.189668,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,NaN,VTO,NaN,NaN,NaN,NaN,0,100,0,490,0,0,0,0,0,0,0,0,29-03-2013
311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013
312,NaN,Chú thích (Note):,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013
313,NaN,(*) : KL được phép sở hữu = KLNY trên HOSE \n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013
314,NaN,(*) : Total room = Listing share\n % S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013

In [57]:
DTNN.to_excel('GDKN-2011-2012-2013q1.xlsx')

In [58]:
DTNN

,STT,Ticker,Total Room,Current Room,Foreign Owned Ratio,State Owned Ratio,OrderM_Buy_vol.Pre-Open,OrderM_Buy_vol.Cont,OrderM_Buy_vol.Pre-Close,OrderM_Buy_vol.Buying value,OrderM_Sell_vol.Pre-Open,OrderM_Sell_vol.Cont,OrderM_Sell_vol.Pre-Close,OrderM_Sell_vol.Selling-value,Putthrough_Buying_Vol,Putthrough_Buying Val,Putthrough_Selling_Vol.,Putthrough_Selling Va,Date
0,1.0,AAM,5556533.36,5393393.0,1.438645,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
1,2.0,ABT,6667531.43,4544944.0,15.598994,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
2,3.0,ACL,5390000.00,4901958.0,4.436745,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
3,4.0,AGD,3920000.00,3828660.0,1.14175,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
4,5.0,AGF,6301051.12,5627483.0,5.237989,8.189668,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,04-01-2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,NaN,VTO,NaN,NaN,NaN,NaN,0,100,0,490,0,0,0,0,0,0,0,0,29-03-2013
311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013
312,NaN,Chú thích (Note):,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013
313,NaN,(*) : KL được phép sở hữu = KLNY trên HOSE \n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013
314,NaN,(*) : Total room = Listing share\n % S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-03-2013

In [59]:
data = pd.read_excel(r'C:/Users/hieudd/Downloads/DTNN_2011\Thang 01-2011\04-01-2011\04012011 - NDTNN (Foreign Trading).xls', skiprows=4)
data = data.iloc[:,0:13]
data.drop(data.head(1).index,inplace=True)
data.drop(data.tail(2).index,inplace=True)
data.reset_index(inplace=True)
data['Date'] = root[50:]
data.set_axis(['STT','Ticker','Total Room','Current Room','Foreign Owned Ratio',' State Owned Ratio',
                    'OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close',
                    'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close',
                    'Putthrough_Buying_Vol','Putthrough_Selling_Vol.','Date'], axis=1, inplace=True)
data

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/hieudd/Downloads/DTNN_2011\\Thang 01-2011\\04-01-2011\\04012011 - NDTNN (Foreign Trading).xls'

In [ ]:
df = pd.read_excel(r'C:/Users/hieudd/Downloads/DTNN_2011\Thang 01-2011\04-01-2011\NN040111.xls', sheet_name='Chi tiet (Details)', skiprows=10)
df.drop(df.tail(2).index,inplace=True)
df.set_axis(['stt',	'Ticker','KL GD mua thị trường','KL GD mua thị trường %','KL GD bán thị trường',
             'KL GD bán thị trường %','OrderM_Buy_vol.Buying value',
             'GT giao dịch mua toàn thị trường %','OrderM_Sell_vol.Selling-value',
             'GT giao dịch bán toàn thị trường %','KL GD Mua thoa thuan','KL GD Mua thoa thuan %',
             'KL GD Ban thoa thuan','KL GD Ban thoa thuan %','Putthrough_Buying Val',
             'GTr GD mua thoa thuan %','Putthrough_Selling Va','GTr GD bán thoa thuan %'],axis=1, inplace=True)
df

,stt,Ticker,KL GD mua thị trường,KL GD mua thị trường %,KL GD bán thị trường,KL GD bán thị trường %,OrderM_Buy_vol.Buying value,GT giao dịch mua toàn thị trường %,OrderM_Sell_vol.Selling-value,GT giao dịch bán toàn thị trường %,KL GD Mua thoa thuan,KL GD Mua thoa thuan %,KL GD Ban thoa thuan,KL GD Ban thoa thuan %,Putthrough_Buying Val,GTr GD mua thoa thuan %,Putthrough_Selling Va,GTr GD bán thoa thuan %
0,1,APC,1600.0,0.091064,0.0,0.000000,20960.0,0.091231,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,BMC,1120.0,0.070352,8410.0,0.528266,28424.0,0.070720,212483.0,0.528666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,BMI,1000.0,0.349650,0.0,0.000000,15700.0,0.349417,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,BMP,60.0,0.011881,0.0,0.000000,2850.0,0.011881,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,BVH,22490.0,0.895303,0.0,0.000000,1508150.0,0.897644,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,76,VKP,0.0,0.000000,1000.0,0.017899,0.0,0.000000,5300.0,0.017680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76,77,VNE,0.0,0.000000,6350.0,0.013102,0.0,0.000000,69850.0,0.013055,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77,78,VSG,0.0,0.000000,3000.0,0.093604,0.0,0.000000,21300.0,0.092470,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,79,VST,0.0,0.000000,200.0,0.007642,0.0,0.000000,2360.0,0.007764,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,80,BT6,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,216000.0,1.0,216000.0,1.0,15552000.0,1.0,15552000.0,1.0

In [ ]:
cd = pd.merge(data, df ,how='left', on='Ticker')
cd = cd[['STT','Ticker','Total Room','Current Room','Foreign Owned Ratio',' State Owned Ratio',
         'OrderM_Buy_vol.Pre-Open','OrderM_Buy_vol.Cont','OrderM_Buy_vol.Pre-Close','OrderM_Buy_vol.Buying value',
         'OrderM_Sell_vol.Pre-Open','OrderM_Sell_vol.Cont','OrderM_Sell_vol.Pre-Close','OrderM_Sell_vol.Selling-value',
         'Putthrough_Buying_Vol','Putthrough_Buying Val','Putthrough_Selling_Vol.','Putthrough_Selling Va','Date']]
cd

,STT,Ticker,Total Room,Current Room,Foreign Owned Ratio,State Owned Ratio,OrderM_Buy_vol.Pre-Open,OrderM_Buy_vol.Cont,OrderM_Buy_vol.Pre-Close,OrderM_Buy_vol.Buying value,OrderM_Sell_vol.Pre-Open,OrderM_Sell_vol.Cont,OrderM_Sell_vol.Pre-Close,OrderM_Sell_vol.Selling-value,Putthrough_Buying_Vol,Putthrough_Buying Val,Putthrough_Selling_Vol.,Putthrough_Selling Va,Date
0,1,AAM,5556533.36,5393393.0,1.438645,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
1,2,ABT,6667531.43,4544944.0,15.598994,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
2,3,ACL,5390000.00,4901958.0,4.436745,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
3,4,AGD,3920000.00,3828660.0,1.141750,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
4,5,AGF,6301051.12,5627483.0,5.237989,8.189668,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,277,VST,28909675.13,28508451.0,0.680049,60.000000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,2360.0,0.0,0.0,0.0,0.0,30-12-2011
277,278,VTB,5871204.50,5780352.0,0.758238,51.426926,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
278,279,VTF,8832499.41,8828749.0,0.020806,0.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
279,280,VTO,39134666.34,38271659.0,1.080560,51.000000,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,30-12-2011
280,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30-12-2011

In [65]:
quarter_dict = {}

for i in range(2013,2023):
    quarter_dict.update({i:[str(i)+'-Q1',str(i)+'-Q2',str(i)+'-Q3',str(i)+'-Q4']})

quarter_dict

{2013: ['2013-Q1', '2013-Q2', '2013-Q3', '2013-Q4'],
 2014: ['2014-Q1', '2014-Q2', '2014-Q3', '2014-Q4'],
 2015: ['2015-Q1', '2015-Q2', '2015-Q3', '2015-Q4'],
 2016: ['2016-Q1', '2016-Q2', '2016-Q3', '2016-Q4'],
 2017: ['2017-Q1', '2017-Q2', '2017-Q3', '2017-Q4'],
 2018: ['2018-Q1', '2018-Q2', '2018-Q3', '2018-Q4'],
 2019: ['2019-Q1', '2019-Q2', '2019-Q3', '2019-Q4'],
 2020: ['2020-Q1', '2020-Q2', '2020-Q3', '2020-Q4'],
 2021: ['2021-Q1', '2021-Q2', '2021-Q3', '2021-Q4'],
 2022: ['2022-Q1', '2022-Q2', '2022-Q3', '2022-Q4']}

In [67]:
a = quarter_dict.get(2013)[0]
a

'2013-Q1'